version: "3.9"

services:
  web:
    build: .
    container_name: wanderlust_web
    ports:
      - "4500:4500"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: wanderlust_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
